[package]
name = "lunar_launcher_inject"
version = "1.4.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
scopeguard = "1.2.0"
thiserror = "2.0.20"
tungstenite = "0.30.0"

[profile.release]
strip = true
lto = true
opt-level = "z"
